=== Distributome/distributome/trunk/js/Distributome.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.distributome.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://www.distributome.org">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
  <xs:element name="distributome">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:distributions"/>
        <xs:element ref="ns1:relations"/>
        <xs:element ref="ns1:references"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:decimal"/>
      <xs:attribute ref="xsi:schemaLocation" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="distributions">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:distribution"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="distribution">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:name"/>
        <xs:element ref="ns1:type"/>
        <xs:element ref="ns1:model"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ns1:parameter"/>
        <xs:element minOccurs="0" ref="ns1:support"/>
        <xs:element ref="ns1:pdf"/>
        <xs:element minOccurs="0" ref="ns1:mode"/>
        <xs:element ref="ns1:cdf"/>
        <xs:element ref="ns1:qf"/>
        <xs:element minOccurs="0" ref="ns1:pgf"/>
        <xs:element minOccurs="0" ref="ns1:mgf"/>
        <xs:element minOccurs="0" ref="ns1:cf"/>
        <xs:element minOccurs="0" ref="ns1:moments"/>
        <xs:element ref="ns1:mean"/>
        <xs:element ref="ns1:variance"/>
        <xs:element minOccurs="0" ref="ns1:skew"/>
        <xs:element minOccurs="0" ref="ns1:kurt"/>
        <xs:element minOccurs="0" ref="ns1:entropy"/>
        <xs:element ref="ns1:median"/>
        <xs:element ref="ns1:q1"/>
        <xs:element ref="ns1:q3"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ns1:family"/>
        <xs:element minOccurs="0" ref="ns1:cite"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="model" type="xs:string"/>
  <xs:element name="parameter" type="xs:string"/>
  <xs:element name="support" type="xs:string"/>
  <xs:element name="pdf" type="xs:string"/>
  <xs:element name="mode" type="xs:string"/>
  <xs:element name="cdf" type="xs:string"/>
  <xs:element name="qf" type="xs:string"/>
  <xs:element name="pgf" type="xs:string"/>
  <xs:element name="mgf" type="xs:string"/>
  <xs:element name="cf" type="xs:string"/>
  <xs:element name="moments">
    <xs:complexType mixed="true">
      <xs:attribute name="type" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="mean" type="xs:string"/>
  <xs:element name="variance" type="xs:string"/>
  <xs:element name="skew" type="xs:string"/>
  <xs:element name="kurt" type="xs:string"/>
  <xs:element name="entropy" type="xs:string"/>
  <xs:element name="median" type="xs:string"/>
  <xs:element name="q1" type="xs:string"/>
  <xs:element name="q3" type="xs:string"/>
  <xs:element name="family" type="xs:string"/>
  <xs:element name="relations">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:relation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="relation">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:cite"/>
        <xs:element ref="ns1:type"/>
        <xs:element ref="ns1:from"/>
        <xs:element ref="ns1:statement"/>
        <xs:element ref="ns1:to"/>
      </xs:choice>
      <xs:attribute name="id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="from" type="xs:string"/>
  <xs:element name="statement" type="xs:string"/>
  <xs:element name="to" type="xs:string"/>
  <xs:element name="references">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:reference"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reference">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:name"/>
        <xs:element ref="ns1:publisher"/>
        <xs:element ref="ns1:title"/>
        <xs:element ref="ns1:url"/>
        <xs:element ref="ns1:year"/>
        <xs:element ref="ns1:Journal"/>
        <xs:element ref="ns1:address"/>
        <xs:element ref="ns1:author"/>
        <xs:element ref="ns1:doi"/>
        <xs:element ref="ns1:edition"/>
        <xs:element ref="ns1:journal"/>
        <xs:element ref="ns1:number"/>
        <xs:element ref="ns1:page"/>
        <xs:element ref="ns1:report"/>
        <xs:element ref="ns1:volume"/>
      </xs:choice>
      <xs:attribute name="id" use="required"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Journal" type="xs:string"/>
  <xs:element name="address" type="xs:string"/>
  <xs:element name="author">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:publisher"/>
        <xs:element ref="ns1:title"/>
        <xs:element ref="ns1:url"/>
        <xs:element ref="ns1:year"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="doi" type="xs:string"/>
  <xs:element name="edition" type="xs:string"/>
  <xs:element name="journal" type="xs:string"/>
  <xs:element name="number" type="xs:integer"/>
  <xs:element name="page" type="xs:NMTOKEN"/>
  <xs:element name="report" type="xs:string"/>
  <xs:element name="volume" type="xs:integer"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="cite" type="xs:string"/>
  <xs:element name="url" type="xs:anyURI"/>
  <xs:element name="publisher" type="xs:string"/>
  <xs:element name="year" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
</xs:schema>

=== Distributome/distributome/trunk/web_site/Tests/V.4.0/data/Distributome2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../images/Distributome_style.css" type="text/css"?>
<distributome version="1.1"
              xmlns="http://www.distributome.org"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.distributome.org/distributome.xsd">


    <distributions>
        <distribution id="arcsine">
            <name>arcsine distribution</name>
            <name>Levy arcsine distribution</name>
            <type>continuous</type>
            <model>The arcsine distribution models the proportion of time that Brownian motion is positive.</model>
            <support>\(x\in[0,1]\)</support>
            <pdf>\(f(x)=\frac{1}{\pi\sqrt{x(1-x)}}\)</pdf>
            <mode>\(x\in{0,1}\)</mode>
            <cdf>\(F(x)=\frac{2}{\pi}\arcsin\left(\sqrt x\right)\)</cdf>
            <qf>\(Q(p) = \sin^2(\frac{\pi}{2} p), \; p \in (0, 1)\)</qf>
            <mean>\(\frac{1}{2}\)</mean>
            <variance>\(\tfrac{1}{8}\)</variance>
            <skew>\(0\)</skew>
            <kurt>\(-\tfrac{3}{2}\)</kurt>
            <median>\(\frac{1}{2}\)</median>
            <q1>\(\frac{2 - \sqrt{2}}{4}\)</q1>
            <q3>\(\frac{2 + \sqrt{2}}{4}\)</q3>
            <history>Derived by Paul Levy in 1939 as the distribution of proportion of time that Brownian motion is  positive.</history>
            <cite>arnold1980some</cite>
        </distribution>

        <distribution id="Bernoulli">
            <name>Bernoulli distribution</name>
            <type>discrete</type>
            <model>The Bernoulli distribution governs an indicator random variable.</model>
            <parameter>\(p \in [0, 1]\), the probability of the event</parameter>
            <support>\(\{0, 1\}\)</support>
            <pdf>\(f(x) = p^x (1 - p)^{1 - x}, \; x \in \{0, 1\}\)</pdf>
            <mode>\(\lfloor 2 p \rfloor\)</mode>
            <cdf>\(F(x) = (1 - p)^{1 - x}, \; x \in \{0, 1\}\)</cdf>
            <qf>\(Q(p) = F^{-1}(p), \; p \in (0, 1)\) where \(F\) is the distribution function</qf>
            <pgf>\(G(t) = 1 - p + p t, \; t \in (-\infty, \infty)\)</pgf>
            <mgf>\(M(t) = 1 - p + p e^t, \; t \in (-\infty, \infty)\)</mgf>
            <cf>\(\varphi(t) = 1 - p + p e^{i t}, \; t \in (-\infty, \infty)\)</cf>
            <moments type="raw">\(\mu(n) = p, \; n \in \{0, 1, \ldots\}\)</moments>
            <mean>\(p\)</mean>
            <variance>\(p (1-p)\)</variance>
            <skew>\(\frac{1 - 2 p}{\sqrt{p (1 - p)}}\)</skew>
            <kurt>\(\frac{1- 6 p + 6 p^2}{p (1 - p)}\)</kurt>
            <entropy>\(-(1 - p) \ln(1 - p) - p \ln(p)\)</entropy>
            <median>\(Q(\frac{1}{2})\) where \(Q\) is the quantile function</median>
            <q1>\(Q(\frac{1}{4})\) where \(Q\) is the quantile function</q1>
            <q3>\(Q(\frac{3}{4})\) where \(Q\) is the quantile function</q3>
            <family>power series </family>
            <family>exponential</family>
            <history>Named for Jacob Bernoulli</history>
            <cite>marshall1985family</cite>
        </distribution>

        <distribution id="beta">
            <name>beta distribution</name>
            <type>continuous</type>
            <model>The beta distribution is used to model random proportions and probabilities. </model>
            <parameter>\(\alpha \in (0, \infty)\), the left shape parameter</parameter>
            <parameter>\(\beta \in (0, \infty)\), the right shape parameter</parameter>
            <support>\((0, 1)\)</support>
            <pdf>\(\frac{x^{\alpha-1}(1-x)^{\beta-1}} {\mathrm{B}(\alpha,\beta)}\!\)</pdf>
            <mode>\(\frac{\alpha - 1}{\alpha + \beta - 2}; \; \alpha \in (1, \infty), \beta \in (1, \infty)\)</mode>
            <cdf>\(I_x(\alpha,\beta)\!\)</cdf>
            <qf>\(Q(p) = F^{-1}(p), \; p \in (0, 1)\), where \(F\) is the distribution function.</qf>
            <mgf>\(1  +\sum_{k=1}^{\infty} \left( \prod_{r=0}^{k-1} \frac{\alpha+r}{\alpha+\beta+r} \right) \frac{t^k}{k!}\)</mgf>
            <mean>\(\frac{\alpha}{\alpha + \beta}\)</mean>
            <variance>\(\frac{\alpha \beta}{(\alpha + \beta)^2 (\alpha + \beta + 1)}\)</variance>
            <skew>\(\frac{2\,(\beta-\alpha)\sqrt{\alpha+\beta+1}}{(\alpha+\beta+2)\sqrt{\alpha\beta}}\)</skew>
            <kurt>\(\frac{6[(\alpha - \beta)^2 (\alpha +\beta + 1) - \alpha \beta (\alpha + \beta + 2)]}{\alpha \beta (\alpha + \beta + 2) (\alpha + \beta + 3)}\)</kurt>
            <entropy>\(\ln(B(\alpha, \beta)) - (\alpha - 1) \psi(\alpha) - (\beta - 1) \psi(\beta) + (\alpha + \beta - 2) \psi(\alpha + \beta)\) where \(\psi\) is the digamma function</entropy>
            <median>\(\begin{matrix}I_{\frac{1}{2}}^{[-1]}(\alpha,\beta)\text{ (in general) }\\[0.5em] \approx \frac{ \alpha - \tfrac{1}{3} }{ \alpha + \beta - \tfrac{2}{3} }\text{ for }\alpha>1, \beta>1\end{matrix}\)</median>
            <q1>\(Q(\frac{1}{4})\) where \(Q\) is the quantile function</q1>
            <q3>\(Q(\frac{3}{4})\) where \(Q\) is the quantile function</q3>
            <family>exponential</family>
            <cite>mcdonald1995generalization</cite>
        </distribution>

        <distribution id="inverse beta">
            <name>inverse beta distribution</name>
            <type>continuous</type>
            <model>The inverse beta distribution, as the name suggests, is the inverse probability dsitribution of a Beta-distributed variable. </model>
            <parameter>\(\alpha \in (0, \infty)\), the left shape parameter</parameter>
            <parameter>\(\beta \in (0, \infty)\), the right shape parameter</parameter>
            <support>\((0, 1)\)</support>
            <family>exponential</family>
            <cite>mcdonald1995generalization</cite>
        </distribution>

        <distribution id="binomial">
            <name>binomial distribution</name>
            <type>discrete</type>
            <model>The binomial distribution models the number of successes in a fixed number of independent trials each with the same probability of success.</model>
            <parameter>\(n \in \{1, 2, \ldots\}\), the number of trials</parameter>
            <parameter>\(p \in [0, 1]\), the probability of success</parameter>
            <support>\(\{0, 1, \ldots, n\}\)</support>
            <pdf>\(f(x) = {n \choose x} p^x (1 - p)^{n - x}, \; x \in \{0, 1, \ldots, n\}\)</pdf>
            <mode>\(\lfloor (n + 1) p \rfloor\)</mode>
            <cdf>\(F(x) = B(1 - p; n - x, x + 1), \; x \in \{0, 1, \ldots, n\}\) where \(B\) is the incomplete beta function</cdf>
            <qf>\(Q(r) = F^{-1}(r), \; r \in [0, 1]\) where \(F\) is the distribution function</qf>
            <pgf>\(G(t) = (1 - p + p t)^n, \; t \in (-\infty, \infty)\)</pgf>
            <mgf>\(M(t) = (1 - p + p e^t)^n, \; t \in (-\infty, \infty)\)</mgf>
            <cf>\(\varphi(t) = (1 - p + p e^{i t})^n, \; t \in (-\infty, \infty)\)</cf>
            <mean>\(n p\)</mean>
            <variance>\(n p (1 - p)\)</variance>
            <skew>\(\frac{1 - 2 p}{\sqrt{n p (1 - p)}}\)</skew>
            <kurt>\(\frac{1 - 6 p (1 - p)}{n p (1 - p)}\)</kurt>
            <entropy>\(\frac{1}{2} \log_2[2 \pi e n p (1 - p)] + O\left(\frac{1}{n}\right)\)</entropy>
            <median>\(Q(\frac{1}{2})\) where \(Q\) is the quantile function</median>
            <q1>\(Q(\frac{1}{4})\) where \(Q\) is the quantile function</q1>
            <q3>\(Q(\frac{1}{3})\) where \(Q\) is the quantile function</q3>
            <family>power series </family>
            <family>exponential</family>
            <history>The binomial distribution is attributed to Jacob Bernoulli</history>
            <cite>altham1978two</cite>
        </distribution>

        <distribution id="beta-binomial">
            <name>beta-binomial distribution</name>
            <type>discrete</type>
            <model>The beta-binomial distribution arises when the success parameter in the binomial distribution is randomized and given a beta distribution.</model>
            <parameter>\(n \in \{1, 2, \ldots\}\), the number of trials</parameter>
            <parameter>\(a \in (0, \infty)\), the left beta parameter</parameter>
            <parameter>\(b \in (0, \infty)\), the right beta parameter</parameter>
            <support>\(\{0, 1, \ldots, n\}\)</support>
            <pdf>\({n\choose k}\frac{\mathrm{B}(k+\alpha,n-k+\beta)} {\mathrm{B}(\alpha,\beta)}\!\) denotes the rising power of order \( j \)</pdf>
            <cdf>\(F(x) = \sum_0^x f(t), \quad x \in \{0, 1, \ldots, n\}\) where \(f\) is the probability density function</cdf>
            <qf>\(Q(p) = F^{-1}(p), \quad p \in (0, 1)\) where \(F\) is the distribution function</qf>
            <mgf>\(_{2}F_{1}(-n,\alpha;\alpha+\beta;1-e^{t})\!\)</mgf>
            <mean>\(\frac{n\alpha}{\alpha+\beta}\!\)</mean>
            <variance>\(n\frac{n\alpha\beta(\alpha+\beta+n)}{(\alpha+\beta)^2(\alpha+\beta+1)}\!\)</variance>
            <skew>\(\tfrac{(\alpha+\beta+2n)(\beta-\alpha)}{(\alpha+\beta+2)}\sqrt{\tfrac{1+\alpha+\beta}{n\alpha\beta(n+\alpha+\beta)}}\!\)</skew>
            <kurt>\(\frac{(a + b)^2 ( + 1 + b)}{n a b (a + b + 2)(a + b + 3)(a + b + n)} \left[(a + b)(a + b - 1 + 6 n) + 3 a b (n - 2) + 6 n^2 - \frac{3 a b n (6-n)}{a + b} - \frac{18 a b n^2}{(a + b)^2}\right]\)</kurt>
            <median>\(Q(\frac{1}{2})\) where \(Q\) is the quantile function</median>
            <q1>\(Q(\frac{1}{4})\) where \(Q\) is the quantile function</q1>
            <q3>\(Q(\frac{3}{4})\) where \(Q\) is the quantile function</q3>
            <cite>altham1978two</cite>
        </distribution>
		
		<distribution id="beta-negative binomial">
            <name>beta-negative binomial distribution</name>
            <type>discrete</type>
